### PR TITLE
patches with vehicle spawning and optimizations

### PR DESCRIPTION
**Pull request by MunchDevelopment**

### CODE REVIEW

**Comment by LukeWasTakenn** [comment]
What does this fix exactly? Adding a "A" to an event name and changing it everyone doesn't magically make the vehicle props apply.

**Comment by MunchDevelopment** [comment]
> What does this fix exactly? Adding a "A" to an event name and changing it everyone doesn't magically make the vehicle props apply.

It fixed the client and server sided spawning, because two events cant be named the same thing no matter if it is server sided events or client sided events, this fixed the issue for both me and atleast 10 other people that was having this issue.

**Comment by LukeWasTakenn** [comment]
I'll be testing it, but if it was an issue with event names I wouldn't be able to pull out a vehicle and have it's props applied fine every single time, like I said it being very inconsistent kinda makes the event theory not stand. The actual issue is probably that the client doesn't receive the network id of the entity on time so it applies the vehicle props onto nothing. I'll be looking into fixing it.

Also what's the benefit of having useZ set to true compared to having minZ and maxZ values so that people can limit their garage zones accordingly?

**Comment by MunchDevelopment** [comment]
> I'll be testing it, but if it was an issue with event names I wouldn't be able to pull out a vehicle and have it's props applied fine every single time, like I said it being very inconsistent kinda makes the event theory not stand. The actual issue is probably that the client doesn't receive the network id of the entity on time so it applies the vehicle props onto nothing. I'll be looking into fixing it.
> 
> Also what's the benefit of having useZ set to true compared to having minZ and maxZ values so that people can limit their garage zones accordingly?

Use Z fixes the issue of the polyzone/qtarget box zone getting stuck and not working.
It basically improves the performance of a Polyzone, but again this commit was purely suggestion based.

**Comment by LukeWasTakenn** [comment]
Hmm another issue I haven't ran into, I had no reports of it either so I'll keep it as is for now.

I'll be implementing the event name change (although I highly doubt it will actually fix anything) along with other fixes soon, although I won't merge this PR thank you!

**Pull request closed without merging**
